language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master
    - develop

matrix:
  include:
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=4.8 COVERAGE=false
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=4.8 COVERAGE=false
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=5.7 COVERAGE=false
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=6.3 COVERAGE=true
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=4.8 COVERAGE=false
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=4.8 COVERAGE=false
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=5.7 COVERAGE=false
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=6.3 COVERAGE=false
  fast_finish: true

# Composer package installation
install:
  # Install composer packages, will also trigger dump-autoload
  - composer install
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer self-update
  - composer require phpunit/phpunit:$PHP_UNIT_VERSION
  - composer install --no-interaction
#  - mkdir -p build/logs
#  - ls -al

script:
# - vendor/bin/phpunit --group ajax
# - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  # Run codeception tests
  - vendor/bin/codecept run --coverage --coverage-xml

after_success:
  - travis_retry php coveralls.phar -v

cache:
  directories:
  - vendor
  - $HOME/.composer/cache
