language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master
    - develop

matrix:
  include:
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=4.8
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=4.8
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=5.7
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=6.3
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=4.8
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=4.8
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=5.7
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=6.3
  fast_finish: true

# Composer package installation
install:
  # Install composer packages, will also trigger dump-autoload
  - composer install
  # Install WP CLI
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version
  # Install GraphQL Schema Linter
  - npm install -g graphql-schema-linter

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer self-update
  - composer require phpunit/phpunit:$PHP_UNIT_VERSION
  - composer install --no-interaction
  - mkdir -p build/logs
  - ls -al

script:
 - vendor/bin/phpunit --group ajax
  - wp --info
  - cd $WP_CORE_DIR_DIR
  - pwd
  - ls
  - wp graphql generate-static-schema --path=$WP_CORE_DIR_DIR
  - graphql-schema-linter $WP_CORE_DIR_DIR/wp-content/plugins/wp-graphql/schema.graphql

after_success:
  - travis_retry php coveralls.phar -v

cache:
  directories:
  - vendor
  - $HOME/.composer/cache
