language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: never

branches:
  only:
    - master
    - develop

matrix:
  include:
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=4.8
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=4.8
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=5.7
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0 PHP_UNIT_VERSION=6.3
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=4.8
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=4.8
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=5.7
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=1 PHP_UNIT_VERSION=6.3
  fast_finish: true

# Composer package installation
install:
  # Install composer packages, will also trigger dump-autoload
  - composer install
  # Install Apache Setup to serve WP from Travis
  - git clone https://github.com/lucatume/travis-apache-setup.git setup
  # Install coveralls.phar
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer self-update
  - composer require phpunit/phpunit:$PHP_UNIT_VERSION
  - composer install --no-interaction
  - mkdir -p build/logs
  - ls -al

script:
 - vendor/bin/phpunit --group ajax
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
 - sh ./setup/wp-install --dir=/tmp/wordpress \
       --dbname="wordpress_test" --dbuser="root" \
       --dbpass="" --dbprefix=wp_ --domain="wordpress.dev" \
       --title="Test" --admin_user=admin --admin_password=admin \
       --admin_email=admin@wordpress.dev --theme=twentysixteen --empty
 - sudo sh ./setup/apache-setup -h="127.0.0.1" -u="http://wp.local" -f"/tmp/wordpress"
 - wget http://wp.local

after_success:
  - travis_retry php coveralls.phar -v

cache:
  directories:
  - vendor
  - $HOME/.composer/cache
