name: WordPress Coding Standards

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    name: Check code
    strategy:
      matrix:
        php: [ 7.4 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl
          tools: composer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ matrix.php }}-${{ runner.os }}-composer

      - name: Install dependencies
        run: |
          composer require --dev \
            phpcompatibility/phpcompatibility-wp \
            wp-coding-standards/wpcs \
            dealerdirect/phpcodesniffer-composer-installer

      - name: Run PHP_CodeSniffer
        run: composer run-script check-cs
